### ISSUE TITLE
Exception thrown on none http/https scheme

### ISSUE THREAD

**Issue by novastream** [TurnerSoftware/InfinityCrawler#132]
When crawling an exception is thrown when processing mailto links for example.

This is fixed by implementing your own RequestProcessor
https://github.com/TurnerSoftware/InfinityCrawler/blob/main/src/InfinityCrawler/Processing/Requests/DefaultRequestProcessor.cs

And checking the uri in the Add method like this
https://stackoverflow.com/a/7581824

**Comment by Turnerj** [comment]
Hey @novastream - thanks for raising this issue! Yeah, it definitely should be checking that.

**Comment by Turnerj** [comment]
I've released a new version (0.5.0) which contains the fix for this!
