### ISSUE TITLE
Update NuGet package 

### ISSUE THREAD

**Issue by djary** [TurnerSoftware/InfinityCrawler#62]
It does not seem to be updated.
https://www.nuget.org/packages/InfinityCrawler

this package work on net5.0?

**Comment by Turnerj** [comment]
Hey @djary - it targets .NET Standard 2.0 which has support through to .NET 5.

You can see the full support matrix here: https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by djary** [comment]
Nice !
