### ISSUE TITLE
Javascript Support

### ISSUE THREAD

**Issue by ghisbo** [TurnerSoftware/InfinityCrawler#87]
Hello, can the infinityCrawler cawl javascript websites ?

**Comment by Turnerj** [comment]
Hey @ghisbo , currently it doesn't support Javascript directly. If you replace the default content processor, you could use AngleSharp and with it, Javascript, to process the page.

I don't have instructions on how to do it but it is possible.

**Comment by ghisbo** [comment]
i am not capable to implement that but thanks for your speedy reply.

**Comment by Turnerj** [comment]
Sorry to hear that - having Javascript support out-of-the-box is a good but yeah, I just haven't implemented leaving the only way to use it by replacing the content processor.

While it won't necessarily make it happen any faster, I will open an issue to track moving to AngleSharp where JS support would be more plug-and-play.
